// <auto-generated />
using System;
using BlazorHotelH2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorHotelH2.Migrations
{
    [DbContext(typeof(HotelH2Context))]
    [Migration("20230831114024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorHotelH2.Models.Administrator", b =>
                {
                    b.Property<int>("adminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adminId"));

                    b.Property<string>("adminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Booking", b =>
                {
                    b.Property<int>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingId"));

                    b.Property<int?>("customerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("bookingId");

                    b.HasIndex("customerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Customer", b =>
                {
                    b.Property<int>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creditCardInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personCount")
                        .HasColumnType("int");

                    b.HasKey("customerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Picture", b =>
                {
                    b.Property<int>("pictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pictureId"));

                    b.Property<string>("pictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("roomId")
                        .HasColumnType("int");

                    b.HasKey("pictureId");

                    b.HasIndex("roomId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Room", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roomId"));

                    b.Property<int>("maxPeople")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("roomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("vacancy")
                        .HasColumnType("bit");

                    b.HasKey("roomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int>("administratorsadminId")
                        .HasColumnType("int");

                    b.Property<int>("customerscustomerId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("administratorsadminId");

                    b.HasIndex("customerscustomerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Booking", b =>
                {
                    b.HasOne("BlazorHotelH2.Models.Customer", null)
                        .WithMany("bookings")
                        .HasForeignKey("customerId");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Picture", b =>
                {
                    b.HasOne("BlazorHotelH2.Models.Room", null)
                        .WithMany("pictures")
                        .HasForeignKey("roomId");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.User", b =>
                {
                    b.HasOne("BlazorHotelH2.Models.Administrator", "administrators")
                        .WithMany()
                        .HasForeignKey("administratorsadminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorHotelH2.Models.Customer", "customers")
                        .WithMany()
                        .HasForeignKey("customerscustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("administrators");

                    b.Navigation("customers");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Customer", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("BlazorHotelH2.Models.Room", b =>
                {
                    b.Navigation("pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
